#!/bin/bash

#Create log files
touch /var/log/geo2tag.log
chmod a+rw /var/log/geo2tag.log


/usr/sbin/adduser --quiet --system geo2tag

create_db_user() {

	sudo -u postgres createuser -s geo2tag
	echo "sudo -u postgres psql --command=\"ALTER USER"
	sudo -u postgres psql --command="ALTER USER geo2tag WITH PASSWORD 'geo2tag';"
}

create_db() {
	sudo -u postgres createdb -O geo2tag geo2tag
	sudo -u postgres psql --command="GRANT ALL privileges on database geo2tag to geo2tag;"
	psql geo2tag -U geo2tag < /opt/geo2tag/db/base.sql
  psql geo2tag -U geo2tag < /opt/geo2tag/base.sql
}

/etc/init.d/lighttpd stop
/etc/init.d/postgresql restart
/etc/init.d/lighttpd start

# down will be DB initialization
# check is there geo2tag db and user
isUserExists=`sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='geo2tag'"`
isDbExists=`sudo -u postgres psql -A -q -t -c "select datname from pg_database" template1 | grep geo2tag`;
if [[ -n "$isUserExists" ]] 
then
	echo "User exists"
	if [[ -n "$isDbExists" ]] 
	then
		echo "Db exists"
		exit 0;
	else
		echo "Db does not exist"
		create_db
	fi
else 
	echo "User does not exist"
	create_db_user
	create_db
fi

sudo /etc/init.d/postgresql restart
sudo /etc/init.d/lighttpd restart;

