#!/bin/bash

TIME=`date +%Y%m%d%H%M%S`;
VERSION=`cat /opt/geo2tag/VERSION`
GIT=`cat /opt/geo2tag/HEAD`


update_pg_config()
{
	pg_hba_pos=`find /etc/postgresql -name pg_hba.conf`;
	pg_hba_us="/opt/geo2tag/conf/pg_hba.conf";

	echo "Replace ${pg_hba_pos} <- ${pg_hba_us}"

	echo "sudo -u postgres psql --command=\"ALTER USER"

	# if more than one pg_hba.conf found
	if [[ "`echo $pg_hba_pos | wc -w`" != "1" ]]
	then

		echo "You have more than one (or no) pg_hba.conf or multiple versions of Postgres installed .  Use $pg_hba_us as example to configure your pg_hba.conf"

	# if content of user pg_hba.conf differs from us
	# ask him does he want to replace it
	# If user want to replace - replace and keep his file
	elif [[ -n "`diff $pg_hba_us $pg_hba_pos`"  ]]
	then
		echo "Replace $pg_hba_pos (if your are installing Geo2Tag for the first time type or you are not sure Y) [Y/n] ?"
		read answ
		echo "Answer is $answ"
		if [[ "$answ" == "y" ]] || [[ "$answ" == "Y" ]] || [[ "$answ" == "" ]]
		then
			mv "$pg_hba_pos" "$pg_hba_pos.backup"
			mv "$pg_hba_us" "$pg_hba_pos"
			 /etc/init.d/postgresql restart
		else
			echo "Use $pg_hba_us as example to configure your pg_hba.conf" 
		fi
	fi
}

create_db_user()
{
	sudo -u postgres createuser -s geo2tag

	sudo -u postgres psql --command="ALTER USER geo2tag WITH PASSWORD 'geo2tag';"
}

create_db() {
	sudo -u postgres createdb -O geo2tag ${DB_NAME}
	sudo -u postgres psql --command="GRANT ALL privileges on database ${DB_NAME} to geo2tag;"
	psql ${DB_NAME} -U geo2tag < /opt/geo2tag/db/base.sql
}

make_default_config()
{
 mv /opt/geo2tag/geo2tag.conf /opt/geo2tag/geo2tag.conf.${TIME}
 CONFIG="cat <<EOF
`cat /opt/geo2tag/geo2tag.conf.template`
EOF"
 eval "$CONFIG" > /opt/geo2tag/geo2tag.conf
}


/etc/init.d/lighttpd stop

update_pg_config

/etc/init.d/postgresql restart

# down will be DB initialization
# check is there geo2tag db and user
isUserExists=`sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='geo2tag'"`
isDbExists=`sudo -u postgres psql -A -q -t -c "select datname from pg_database" template1 | grep geo2tag`;

if [[ -n "$isDbExists" ]] 
then

	DB_NAME="geo2tag${TIME}"
	echo "Db exists. Generated name ${DB_NAME}"
else
	echo "Db does not exist"
	DB_NAME="geo2tag"
fi

if [[ -n "$isUserExists" ]] 
then
	echo "User exists"
else 
	echo "User does not exist"
	create_db_user
fi

create_db
make_default_config



sudo /etc/init.d/lighttpd start;

echo "======================================================================"
echo "                      PLEASE READ AND UNDERSTAND  "
echo "======================================================================"
echo "Note: new instance of Geo2tag DB was created. Instance name ${DB_NAME}"
echo "Please check db name in /opt/geo2tag/geo2tag.conf file and restart"
echo "lighttpd service if required:"
echo "       sudo /etc/init.d/lighttpd restart"
echo "   "
